[phases.setup]
nixPkgs = ['nodejs-20_x', 'npm-9_x']

[phases.build]
cmds = [
    'npm ci --only=production',
    'npm run build'
]

[phases.deploy]
cmd = 'npm run start:prod'

[variables]
NODE_ENV = 'production'
