// Seed script to populate database with base skills
// Run this after creating the skill_definitions table

const baseSkills = [
  // Basic Skills (Low requirements for new players)
  {
    skillId: 'basic_training',
    name: 'Basic Training',
    description: 'Fundamental combat training that slightly increases all stats',
    maxLevel: 3,
    requiredAttribute: 'STR',
    requiredAttributeValue: 1,
    requiredLevel: 1,
    skillPointCost: 1,
    category: 'Combat',
    sortOrder: 1,
    effects: {
      1: { statBonuses: { attack: 0.02, defense: 0.02, maxHp: 0.02 } },
      2: { statBonuses: { attack: 0.04, defense: 0.04, maxHp: 0.04 } },
      3: { statBonuses: { attack: 0.06, defense: 0.06, maxHp: 0.06 } },
    },
  },
  {
    skillId: 'power_strike',
    name: 'Power Strike',
    description: 'Increases attack power',
    maxLevel: 5,
    requiredAttribute: 'STR',
    requiredAttributeValue: 20,
    requiredLevel: 1,
    skillPointCost: 1,
    category: 'Combat',
    sortOrder: 2,
    effects: {
      1: { statBonuses: { attack: 0.05 } },
      2: { statBonuses: { attack: 0.1 } },
      3: { statBonuses: { attack: 0.15 } },
      4: { statBonuses: { attack: 0.2 } },
      5: { statBonuses: { attack: 0.25 } },
    },
  },
  {
    skillId: 'guardian',
    name: 'Guardian',
    description: 'Increases defense',
    maxLevel: 3,
    requiredAttribute: 'STR',
    requiredAttributeValue: 30,
    requiredLevel: 5,
    skillPointCost: 2,
    category: 'Combat',
    sortOrder: 3,
    effects: {
      1: { statBonuses: { defense: 0.1 } },
      2: { statBonuses: { defense: 0.2 } },
      3: { statBonuses: { defense: 0.3 } },
    },
  },
  {
    skillId: 'berserker',
    name: 'Berserker',
    description: 'Increases critical damage but reduces defense',
    maxLevel: 3,
    requiredAttribute: 'STR',
    requiredAttributeValue: 40,
    requiredLevel: 10,
    skillPointCost: 3,
    category: 'Combat',
    sortOrder: 4,
    effects: {
      1: { statBonuses: { critDamage: 15, defense: -0.1 } },
      2: { statBonuses: { critDamage: 30, defense: -0.15 } },
      3: { statBonuses: { critDamage: 45, defense: -0.2 } },
    },
  },

  // Magic Mastery (INT-focused)
  {
    skillId: 'arcane_power',
    name: 'Arcane Power',
    description: 'Increases magic attack power',
    maxLevel: 5,
    requiredAttribute: 'INT',
    requiredAttributeValue: 20,
    requiredLevel: 1,
    skillPointCost: 1,
    category: 'Magic',
    sortOrder: 5,
    effects: {
      1: { statBonuses: { attack: 0.06 } },
      2: { statBonuses: { attack: 0.12 } },
      3: { statBonuses: { attack: 0.18 } },
      4: { statBonuses: { attack: 0.24 } },
      5: { statBonuses: { attack: 0.3 } },
    },
  },
  {
    skillId: 'mana_shield',
    name: 'Mana Shield',
    description: 'Converts intelligence to defense',
    maxLevel: 3,
    requiredAttribute: 'INT',
    requiredAttributeValue: 30,
    requiredLevel: 5,
    skillPointCost: 2,
    category: 'Magic',
    sortOrder: 6,
    effects: {
      1: { statBonuses: { defense: 0.15 } },
      2: { statBonuses: { defense: 0.25 } },
      3: { statBonuses: { defense: 0.35 } },
    },
  },
  {
    skillId: 'spell_echo',
    name: 'Spell Echo',
    description: 'Chance to cast spells twice',
    maxLevel: 3,
    requiredAttribute: 'INT',
    requiredAttributeValue: 40,
    requiredLevel: 10,
    skillPointCost: 3,
    category: 'Magic',
    sortOrder: 7,
    effects: {
      1: { specialEffects: ['spell_echo_15'] },
      2: { specialEffects: ['spell_echo_25'] },
      3: { specialEffects: ['spell_echo_35'] },
    },
  },

  // Agility Mastery (DEX-focused)
  {
    skillId: 'swift_strikes',
    name: 'Swift Strikes',
    description: 'Increases attack speed',
    maxLevel: 5,
    requiredAttribute: 'DEX',
    requiredAttributeValue: 20,
    requiredLevel: 1,
    skillPointCost: 1,
    category: 'Agility',
    sortOrder: 8,
    effects: {
      1: { statBonuses: { attack: 0.03 } },
      2: { statBonuses: { attack: 0.06 } },
      3: { statBonuses: { attack: 0.09 } },
      4: { statBonuses: { attack: 0.12 } },
      5: { statBonuses: { attack: 0.15 } },
    },
  },
  {
    skillId: 'evasion',
    name: 'Evasion',
    description: 'Increases dodge rate',
    maxLevel: 3,
    requiredAttribute: 'DEX',
    requiredAttributeValue: 30,
    requiredLevel: 5,
    skillPointCost: 2,
    category: 'Agility',
    sortOrder: 9,
    effects: {
      1: { statBonuses: { dodgeRate: 10 } },
      2: { statBonuses: { dodgeRate: 20 } },
      3: { statBonuses: { dodgeRate: 30 } },
    },
  },
  {
    skillId: 'combo_master',
    name: 'Combo Master',
    description: 'Increases combo rate',
    maxLevel: 3,
    requiredAttribute: 'DEX',
    requiredAttributeValue: 40,
    requiredLevel: 10,
    skillPointCost: 3,
    category: 'Agility',
    sortOrder: 10,
    effects: {
      1: { statBonuses: { comboRate: 25 } },
      2: { statBonuses: { comboRate: 40 } },
      3: { statBonuses: { comboRate: 55 } },
    },
  },

  // Vitality Mastery (VIT-focused)
  {
    skillId: 'toughness',
    name: 'Toughness',
    description: 'Increases maximum HP',
    maxLevel: 5,
    requiredAttribute: 'VIT',
    requiredAttributeValue: 20,
    requiredLevel: 1,
    skillPointCost: 1,
    category: 'Vitality',
    sortOrder: 11,
    effects: {
      1: { statBonuses: { maxHp: 0.05 } },
      2: { statBonuses: { maxHp: 0.1 } },
      3: { statBonuses: { maxHp: 0.15 } },
      4: { statBonuses: { maxHp: 0.2 } },
      5: { statBonuses: { maxHp: 0.25 } },
    },
  },
  {
    skillId: 'regeneration',
    name: 'Regeneration',
    description: 'HP regeneration over time',
    maxLevel: 3,
    requiredAttribute: 'VIT',
    requiredAttributeValue: 30,
    requiredLevel: 5,
    skillPointCost: 2,
    category: 'Vitality',
    sortOrder: 12,
    effects: {
      1: { specialEffects: ['hp_regen_1'] },
      2: { specialEffects: ['hp_regen_2'] },
      3: { specialEffects: ['hp_regen_3'] },
    },
  },
  {
    skillId: 'pain_tolerance',
    name: 'Pain Tolerance',
    description: 'Reduces damage taken',
    maxLevel: 3,
    requiredAttribute: 'VIT',
    requiredAttributeValue: 40,
    requiredLevel: 10,
    skillPointCost: 3,
    category: 'Vitality',
    sortOrder: 13,
    effects: {
      1: { specialEffects: ['damage_reduction_5'] },
      2: { specialEffects: ['damage_reduction_10'] },
      3: { specialEffects: ['damage_reduction_15'] },
    },
  },

  // Luck Mastery (LUK-focused)
  {
    skillId: 'fortune',
    name: 'Fortune',
    description: 'Increases critical rate',
    maxLevel: 5,
    requiredAttribute: 'LUK',
    requiredAttributeValue: 20,
    requiredLevel: 1,
    skillPointCost: 1,
    category: 'Luck',
    sortOrder: 14,
    effects: {
      1: { statBonuses: { critRate: 3 } },
      2: { statBonuses: { critRate: 6 } },
      3: { statBonuses: { critRate: 9 } },
      4: { statBonuses: { critRate: 12 } },
      5: { statBonuses: { critRate: 15 } },
    },
  },
  {
    skillId: 'lucky_charm',
    name: 'Lucky Charm',
    description: 'Increases item drop rate',
    maxLevel: 3,
    requiredAttribute: 'LUK',
    requiredAttributeValue: 30,
    requiredLevel: 5,
    skillPointCost: 2,
    category: 'Luck',
    sortOrder: 15,
    effects: {
      1: { specialEffects: ['drop_rate_10'] },
      2: { specialEffects: ['drop_rate_20'] },
      3: { specialEffects: ['drop_rate_30'] },
    },
  },
  {
    skillId: 'gamble',
    name: 'Gamble',
    description: 'Random stat boost on enemy kill',
    maxLevel: 3,
    requiredAttribute: 'LUK',
    requiredAttributeValue: 40,
    requiredLevel: 10,
    skillPointCost: 3,
    category: 'Luck',
    sortOrder: 16,
    effects: {
      1: { specialEffects: ['gamble_1'] },
      2: { specialEffects: ['gamble_2'] },
      3: { specialEffects: ['gamble_3'] },
    },
  },

  // Active Skills
  {
    skillId: 'quick_attack',
    name: 'Quick Attack',
    description: 'A fast basic attack that deals light damage',
    maxLevel: 5,
    requiredAttribute: 'STR',
    requiredAttributeValue: 5,
    requiredLevel: 1,
    skillPointCost: 1,
    category: 'Combat',
    sortOrder: 17,
    skillType: 'active',
    manaCost: 5,
    cooldown: 2,
    targetType: 'enemy',
    damageType: 'physical',
    damageFormula: 'STR * 0.8 + level * 5',
    effects: {
      1: { damage: 15 },
      2: { damage: 20 },
      3: { damage: 25 },
      4: { damage: 30 },
      5: { damage: 35 },
    },
  },
  {
    skillId: 'fireball',
    name: 'Fireball',
    description: 'Launches a magical fireball at an enemy',
    maxLevel: 5,
    requiredAttribute: 'INT',
    requiredAttributeValue: 25,
    requiredLevel: 3,
    skillPointCost: 2,
    category: 'Magic',
    sortOrder: 18,
    skillType: 'active',
    manaCost: 20,
    cooldown: 3,
    targetType: 'enemy',
    damageType: 'magical',
    damageFormula: 'INT * 1.5 + level * 15',
    effects: {
      1: { damage: 50 },
      2: { damage: 75 },
      3: { damage: 100 },
      4: { damage: 125 },
      5: { damage: 150 },
    },
  },
  {
    skillId: 'heal',
    name: 'Heal',
    description: 'Restores HP to self or ally',
    maxLevel: 5,
    requiredAttribute: 'INT',
    requiredAttributeValue: 30,
    requiredLevel: 5,
    skillPointCost: 2,
    category: 'Magic',
    sortOrder: 19,
    skillType: 'active',
    manaCost: 25,
    cooldown: 4,
    targetType: 'ally',
    healingFormula: 'INT * 1.2 + level * 20',
    effects: {
      1: { healing: 60 },
      2: { healing: 90 },
      3: { healing: 120 },
      4: { healing: 150 },
      5: { healing: 180 },
    },
  },
  {
    skillId: 'taunt',
    name: 'Taunt',
    description: 'Forces enemy to attack you for several turns',
    maxLevel: 3,
    requiredAttribute: 'STR',
    requiredAttributeValue: 35,
    requiredLevel: 7,
    skillPointCost: 3,
    category: 'Combat',
    sortOrder: 20,
    skillType: 'active',
    manaCost: 15,
    cooldown: 5,
    targetType: 'enemy',
    effects: {
      1: { debuffDuration: 2 },
      2: { debuffDuration: 3 },
      3: { debuffDuration: 4 },
    },
  },
];

module.exports = baseSkills;